spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_estate_db
    username: dheya
    password: 7800
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect